server:
  port: 8000

spring:
  application:
    name: msa_gatewayservice
  config:
    import: "optional:file:/app/config/application.yml"

  cloud:
    gateway:
      routes:
        - id: finalProject_3
          uri: http://localhost:9080
          predicates:
            - Path=/finalProject_3/**

        - id: board_service
          uri: http://localhost:8002
          predicates:
            - Path=/board-service/**
          filters:
            - RewritePath=/board-service/(?<segment>.*), /${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix.discovery: WARN
